### ISSUE TITLE
[BUG] Gravity off event in a planet?

### ISSUE THREAD

**Issue by AGasCanister** [PersistentSS13/Nebula#101]
![image](https://user-images.githubusercontent.com/55928412/95348261-25727a80-08be-11eb-8244-d782b4f7f7e6.png)

Basically this can happen in the starting planet

**Comment by biscuitWizard** [comment]
amazing

**Comment by PsyCommando** [comment]
This shouldn't occur anymore. Exoplanets aren't considered station levels anymore.
