### ISSUE TITLE
[Tuning] The nuclear fabricator and more blueprint instability than Ugandas Economy

### ISSUE THREAD

**Issue by thestalker12** [PersistentSS13/Nebula#124]
#### Description of issue
So if you got a fabricator and do ANY OF THE EXPERIMENTS the instability will sky rocket to something around 200+%
Nuclear fabricator: When you produce said item from the fabricator and stand near the explosion you get the following results
https://i.gyazo.com/989cb3d476cc51664672be02d3dc5156.png
https://i.gyazo.com/ed45ee760056f0054e2305fcc52baf1a.png
https://gyazo.com/80241464a019ce0e04e5731bd2a188d2
#### Difference between expected and actual behavior
Expected behavior is not turning myself into a semi functional set of gibs. As well not having instability sky rocket to levels outside any normal bounds

#### Steps to reproduce
Do an experiment in the experimentation menu with any science level. Wrap it up and fulfill the items break down requirement.
Then check the instability rating. 
Now on the nuclear fabricator, produce said unstable object thus creating profit
#### Specific information for locating

Fabricator
Blueprint/DA menu on consoles

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: Revision Unknown
Game ID: b0U-aPIh
Current map: Outreach Outpost

#### Issue bingo
- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by thestalker12** [comment]
Following notes: The gif shown is with instability 372% which was gained from one experiment which was considered minor

**Comment by PsyCommando** [comment]
RnD was remade.
