### ISSUE TITLE
[BUG] No Facial Hair

### ISSUE THREAD

**Issue by Crezilin** [PersistentSS13/Nebula#166]
#### Description of issue
When making a character you click the button to open the type of facial hair that you want. It doesn't work.

#### Difference between expected and actual behavior
The behavior is that nothing happens when clicking on the facial hair button.
The button is supposed to open up a list you can scroll through to select a facial hair type.

#### Steps to reproduce
Click on the facial hair button in character creation.

#### Issue bingo

- [X ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X ] Issue could be reproduced in multiple rounds
- [X ] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
Been fixed.
