### ISSUE TITLE
[BUG]  Cryopod Security

### ISSUE THREAD

**Issue by Crezilin** [PersistentSS13/Nebula#168]
#### Description of issue
You may be removed from cryo pods / you cannot lock them / probably also still easily damaged.

#### Difference between expected and actual behavior
Since someone cannot despawn then cryo pods are supposed to essentially "lock" whether automatically or manually I don't know. However, they're supposed to be secure. Specifically, the issue is that I can remove people from them.
They should have a locking button or auto-lock and should be made indestructible while occupied. I would also recommend that if someone stays in one for 30 real life days then the cryopod will automatically deactivate its locking mechanism. 

#### Steps to reproduce
Go up to a crypod and remove someone or have someone remove you from a cryopod.

#### Length of time in which bug has been known to occur
6+ months.

#### Client version, Server revision & Game ID
The current one that we're using for testing.

#### Issue bingo

- [] Issue could be reproduced at least once
- [] Issue could be reproduced by different players
- [] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Kurgis** [comment]
Problem is each cryopod takes a 1x1 space while we can expect hundreds of unique players, it'd be nice if we had a bulk storage solution.

**Comment by ghost** [comment]
I was told bulk storage wasn't an option because it causes "instability".

**Comment by NataKilar** [comment]
Not really a bug per se, but a design oversight. After this first round of open testing, it seems extremely unfeasible to keep players in world at all due to mob processing. By full launch, we'll have hopefully moved entirely to experimental cryopods to remove players from the game.

**Comment by PsyCommando** [comment]
Cryopods now despawn occupants, so this is not an issue anymore.
