### ISSUE TITLE
[OVERSIGHT] You cannot obtain botanical bags in-gameplay

### ISSUE THREAD

**Issue by Kurgis** [PersistentSS13/Nebula#171]
#### Description of issue

Can't get botanical bags, entire server becomes giant mess of items and plants covering the entire place, causing even more strain on keeping things clean.

#### Difference between expected and actual behavior

I have botanical bag, I produced it from biogenerator for some biomass, I can now manage the horrible mess that is hundreds of seeds and plants. Seeds and plants are all over the place, unmanageable, in desperation after finding that they're unobtainable I adminhelped for a bag which helped me delete about ~100 useless seeds, and clean everything.

#### Steps to reproduce

Play botany.

#### Specific information for locating

https://github.com/PersistentSS13/Nebula/blob/dev/code/game/objects/items/weapons/storage/specialized.dm#L54

#### Length of time in which bug has been known to occur

Forever.

#### Client version, Server revision & Game ID

513 - cae48ed581a783fad60ce376bac09a1c521ff06f - ccT-cSuk

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
Added upstream.
