### ISSUE TITLE
Cryopod occupants may not eject themselves

### ISSUE THREAD

**Issue by Kurgis** [PersistentSS13/Nebula#173]
#### Description of issue

I entered my character into a cryopod, the character then stayed inside said pod without logging out for some time until they eventually got messages telling them they are going to fall asleep essentially. Once this happened, the character became unconscious and was no longer able to interact with objects, namely, the cyrogenic freezer they're stuck in.

#### Difference between expected and actual behavior

Entering and exiting the sleeper unaided from external forces; logging back in and asking for help in cortical chat for someone to pop open the door.

#### Steps to reproduce

Strangely, I've entered the cryopod, logged off immediately, and logged back on some time later with no issue. Either this is some issue with the server running a long time (doubtful), or a previously unknown feature where cryogenic freezers will knock out anyone inside permanently if their ckey idles inside the pod for too long.

#### Specific information for locating

https://github.com/PersistentSS13/Nebula/blob/dev/code/game/machinery/cryopod.dm

#### Length of time in which bug has been known to occur

Since the latter part of this test.

#### Client version, Server revision & Game ID

513 - cae48ed - ccT-cSuk

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
That was due to another problem with saving in cryopods. Should have been fixed by now.
