### ISSUE TITLE
[BUG] Chemical Heater/Coolers cannot be constructed

### ISSUE THREAD

**Issue by PipeWizard** [PersistentSS13/Nebula#180]
#### Description of issue
The chemical heater/cooler doesn't want to accept any components that it requires.  Can't interact with tools besides wrenching and unwrenching it either so you can't deconstruct it.
Likely a Nebula problem as well.

#### Difference between expected and actual behavior
Obvious ^^

#### Steps to reproduce
Try and build one

#### Specific information for locating

Chemical Cooler

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
Should be fixed
