### ISSUE TITLE
Heavy Duty Cell Recharger has an unlisted required component

### ISSUE THREAD

**Issue by PipeWizard** [PersistentSS13/Nebula#181]
#### Description of issue
The heavy duty cell recharger needs to have the Battery Backup set to essential component, without it you cannot place batteries
inside of it

#### Difference between expected and actual behavior
No indication of a required component for it to function.

#### Steps to reproduce
Try and build a heavy duty cell recharger.

#### Client version, Server revision & Game ID

Server Revision: cc267968ce9ef5baa29eea25aee2f2afe094cc43 - dev - 2021-07-09
Game ID: ccW-aFEf

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
That's been fixed
