### ISSUE TITLE
Jukebox cuts out as soon as it is no longer visible

### ISSUE THREAD

**Issue by PipeWizard** [PersistentSS13/Nebula#182]
#### Description of issue
The Jukebox cuts out as soon as it is no longer visible despite being within physical range.

#### Difference between expected and actual behavior
Expectation: it to not cut out
Behavior: abrupt cut-off

#### Steps to reproduce
Stand near one, go around a corner or do something to block visual sight

#### Specific information for locating

/code/game/machinery/jukebox.dm

#### Length of time in which bug has been known to occur

Since open testing.

#### Client version, Server revision & Game ID

Server Revision: cc267968ce9ef5baa29eea25aee2f2afe094cc43 - dev - 2021-07-09
Game ID: ccW-aFEf

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
That's a technical limitation of how the jukebox is coded. It uses the view range to play music to mobs. Would  need upstream work to fix that.
