### ISSUE TITLE
[BUG] Deconstructing Battery Rack PSU units can leave ghost terminals

### ISSUE THREAD

**Issue by wasakoki** [PersistentSS13/Nebula#185]
#### Description of issue
You are able to fully deconstruct a battery Rack PSU unit without needing to disconnect a terminal from it. this causes an issue where the terminals remain and cannot be destroyed due to no longer being linked to a machine.

#### Difference between expected and actual behavior
expected behavior: when attempting to dismantle a PSU unit (final step, crowbar), the game should prevent you from doing so, and notify you must remove the terminal first.

#### Steps to reproduce
1. build a battery rack PSU unit
2. connect a terminal by clicking on the PSU unit with wires
3. after the terminal is built, deconstruct the PSU unit with a crowbar

#### Specific information for locating

machine name when placed down: "power cell rack PSU"

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: cc267968ce9ef5baa29eea25aee2f2afe094cc43 - dev - 2021-07-09
Game ID: ccW-aFEf

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
It wasn't a ghost terminal, it's just the construction states getting messed up. Should be fixed.
