### ISSUE TITLE
[suggestion] remove high tech hydroponic tray starter kit in favor for low tech planting beds

### ISSUE THREAD

**Issue by wasakoki** [PersistentSS13/Nebula#188]
to go along with the theme of a "barebones" starting outpost, the hydroponics kit (containing a circuit for a hydroponics tray) could be removed in favor for the low tech dirt plots. This "low tech" alternative does not have indicators for low water/nutrition/maturity but otherwise function almost exactly the same to my knowledge. The ability to build these is already possible with all stone-based ores via handcrafting _[stone type] planting bed (3 bricks)_ (in the case of Kleibkhar, sandstone obtained from the mines), so to implement this suggest the only that would need to be done is to remove the existing vendor kit.

**Comment by PsyCommando** [comment]
That doesn't work for outreach. But hydroponics could use some sort of tech tiers I guess in the future. It would need to be part of a larger change though, since it's not very flexible currently.
