### ISSUE TITLE
[BUG] Large Beaker and buckets not saving contents on server restart

### ISSUE THREAD

**Issue by wasakoki** [PersistentSS13/Nebula#196]
#### Description of issue
Yesterday i had a bucket of water and a beaker of flour. today i joined the server and the contents of these containers are now empty.

#### Difference between expected and actual behavior
their contents should save

#### Steps to reproduce
1. print containers
2. fill containers with liquid
3. save server
4. restart server
5. containers will be empty upon reload

#### Specific information for locating

"glass large beaker"
"bucket" (currently the item name is "bucket of water" since it had water it in and i'm guessing the name saved)

#### Client version, Server revision & Game ID

Server Revision: 304cb031394d693342d4d73273bfb1d84d931beb - dev - 2021-07-10
Game ID: ccX-cyF6
Current map: Kleibkhar C

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by wasakoki** [comment]
will update issue bingo if it happens again on next server save/restart

**Comment by PsyCommando** [comment]
Should be fixed, since we're saving reagents now.
