### ISSUE TITLE
[Oversight] incorrect initial skill point amount notification when choosing a career with offset points

### ISSUE THREAD

**Issue by wasakoki** [PersistentSS13/Nebula#199]
this PR gave the ability for background & professions to have skill point offsets: https://github.com/PersistentSS13/Nebula/pull/186

there is a (very) minor oversight with the implementation, the new character join text is still hardcoded to show 30 skill points upon joining:
![image](https://user-images.githubusercontent.com/65874132/125182352-faadad80-e1d2-11eb-8057-e37518071ca7.png)
![image](https://user-images.githubusercontent.com/65874132/125182486-f8981e80-e1d3-11eb-924c-908571d3965b.png)

**Comment by PipeWizard** [comment]
Will fix later tonight, thanks
