### ISSUE TITLE
[BUG] going to the edge of a temporary z-level does weird stuff

### ISSUE THREAD

**Issue by wasakoki** [PersistentSS13/Nebula#204]
#### Description of issue
when approaching the edge of a z-level, you stay stuck at the edge and all items you interact with are deleted.

i was speaking with Solidyote ingame at the time and they mentioned this:
  _Solidyote: sounds like the game is actually trying to delete you
  Solidyote: its trying to delete the temporary sector you were in_

#### Difference between expected and actual behavior
expected: i should be able to interact with items & they should certainly NOT be deleted, the z-level should probably loop around (?), or at least something that doesn't result in you being stuck on the edge of a z-level

#### Steps to reproduce
fly to open space
go to a z-level edge
interact with any items on your character and watch them be deleted

note/possible hidden step: i encountered this bug at the same z-level when trying to travel a stellar anchor z-level but failed (information can be found here https://github.com/PersistentSS13/Nebula/issues/203 )

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 304cb031394d693342d4d73273bfb1d84d931beb - dev - 2021-07-10
Game ID: ccX-cyF6
Current map: Kleibkhar Colony

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
That was a upstream issue afaik. Temporary transit z-levels weren't being created.
