### ISSUE TITLE
[BUG] Restart of server causes some objects to revert to their default, causing weirdness

### ISSUE THREAD

**Issue by genessee-forgot-his-password-again** [PersistentSS13/Nebula#206]
#### Description of issue

Upon reboot of the server and reloading of a previous save, many items will revert back to their default forms.

For example, piles of credits will be turned into their default amount (usually 0, creating a spriteless glitched item) on restart, making physical money stashes unsafe.

Additionally, many 'variable' foods act strange. Many will change their color to an odd brown shade, while cereal boxes will lose their sprite completely; 
![image](https://user-images.githubusercontent.com/80235421/125253036-f95dad00-e2c6-11eb-8faf-c0f3be13e85b.png)

Smartfridges' stock is no longer displayed, requiring the machine to be rebuilt to manually remove it's stock.

#### Difference between expected and actual behavior

I expected things to stay more or less the same between saves. Instead, things disappeared, bluespace trolls stole my money, and my smartfridges experienced 5G.

#### Steps to reproduce

- Withdraw any amount of money from your bank account
- Save the server
- Reboot and load from the save you made
- Examine your bugged 'credit' with a value of 0

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Since saving has been a thing, as far as I know.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 304cb031394d693342d4d73273bfb1d84d931beb - dev - 2021-07-10
Game ID: ccX-cyF6
Current map: Kleibkhar Colony

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by genessee-forgot-his-password-again** [comment]
I believe the same effects occur when spawning out of the experimental cryopod. Not 100% sure, though.

**Comment by genessee-forgot-his-password-again** [comment]
Still an issue as of 11/20/2021.

**Comment by PsyCommando** [comment]
That's too vague. It's what happens when any single thing doesn't have their vars set to save.
