### ISSUE TITLE
Machine Component Issue List

### ISSUE THREAD

**Issue by PipeWizard** [PersistentSS13/Nebula#210]
Fixes for these should be PR'ed upstream to https://github.com/NebulaSS13/Nebula

#### Component Issue List (machine - problematic component)
- [ ] 1. SMES - Add a statement about the requirement of 1-4 wired terminal components (1 for each direction) to the description on examine during the construction phase. Note: one direction is used for the output and you cannot layer cables.
        /obj/machinery/power/smes/buildable
        /obj/item/stock_part/power/terminal/buildable
- [ ] 2. Pipes - Description for all pipes state they lack power despite not requiring power.
       /obj/machinery/atmospherics/pipe/simple
- [ ] 3. Manual Valves - Require a Tesla Link despite not needing one
       /obj/machinery/atmospherics/valve
- [ ] 4. Heavy Duty Cell Charger - Requires a backup battery but doesn't state this.
       /obj/machinery/cell_charger
       /obj/item/stock_parts/power/battery

**Comment by MahaSaka** [comment]
4. Heavy Duty Cell Chargers - See issue https://github.com/PersistentSS13/Nebula/issues/181 (backup batteries).

**Comment by PsyCommando** [comment]
Should have been fixed upstream.
