### ISSUE TITLE
Cannot make fiberglass windows pane, or windows.

### ISSUE THREAD

**Issue by PsyCommando** [PersistentSS13/Nebula#212]
#### Description of issue
Cannot make fiberglass windows pane, or windows with the construction menu on the material stack

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by thedarkcrusader** [comment]
@PsyCommando Menu won't pop up but i can just use fiberglass on a low wall or a grille to produce the window but it's intended to also be able to be made with the menu, correct?

**Comment by PsyCommando** [comment]
should be

**Comment by PsyCommando** [comment]
I think this was an old persistence only feature.
