### ISSUE TITLE
Air Alarms will not connect to vents

### ISSUE THREAD

**Issue by genessee-forgot-his-password-again** [PersistentSS13/Nebula#218]
#### Description of issue

What it says on the tin. Air alarms cannot connect to air vents in the same room. The vent throws this runtime; 
![image](https://user-images.githubusercontent.com/80235421/125568698-699d4a0c-eb99-47aa-9fca-a9bdb2345cd3.png)

#### Difference between expected and actual behavior

I expected to be able to link air alarms to vents. I was not.

#### Steps to reproduce

- Build a powered room with an APC
- Build a vent inside said room and ensure it has the correct components
- Build a functional air alarm
- Observe the fact that the air alarm will not connect to the vent

#### Specific information for locating

I did this in a space sector and I made sure to have a network functional in my sector. Didn't try building from scratch, only from the kit item.

#### Length of time in which bug has been known to occur

Recently. I can see other functional air alarms around on other builds.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 304cb031394d693342d4d73273bfb1d84d931beb - dev - 2021-07-10
Game ID: cc2-azYy
Current map: Kleibkhar Colony

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
I think its not happening anymore since we updated to upstream
