### ISSUE TITLE
Wall Materials Don't Save

### ISSUE THREAD

**Issue by PipeWizard** [PersistentSS13/Nebula#228]
#### Description of issue
After a Save & Load, walls' materials are reverted back to steel from whatever material they were built with.

#### Difference between expected and actual behavior
It to be the material they were saved with.

#### Steps to reproduce
Save & Load.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue happened in a recent (less than 7 days ago) round

**Comment by PsyCommando** [comment]
Pretty sure that was fixed a while ago. We'll open another if it happens again on the new map.
