### ISSUE TITLE
Lighting weirdness

### ISSUE THREAD

**Issue by genessee-forgot-his-password-again** [PersistentSS13/Nebula#253]
#### Description of issue

Walls created with build mode or an RCD sometimes get weird lighting.

![image](https://user-images.githubusercontent.com/80235421/142735117-abd94d4b-0077-4561-bbfd-133342a5e442.png)
![image](https://user-images.githubusercontent.com/80235421/142735127-691a4641-c58d-42a0-9081-0be050e8e099.png)

#### Difference between expected and actual behavior

I expected these walls to correctly reflect light. Instead, they appear to defy laws of physics.

#### Steps to reproduce

1. Knock down a wall at the Outpost. 
2. Build a new wall in it's place with an RCD or Build Mode.
3. Observe strange lighting.

#### Length of time in which bug has been known to occur

Since 11/20/2021 at 12:12 PM.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 7519422ea6497f6a193ff3398e7985b6961eb9ec - dev - 2021-11-20
Game ID: ce7-cHhm
Current map: Kleibkhar Colony

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
Could be an upstream issue. Will need confirmation its still happening.

**Comment by PsyCommando** [comment]
Was fixed upstream.
