### ISSUE TITLE
Sometimes people become unable to move for no reason at all

### ISSUE THREAD

**Issue by genessee-forgot-his-password-again** [PersistentSS13/Nebula#257]
#### Description of issue

Occasionally, a player will lose the ability to move on their own. The only way to fix this is deleting their character.

#### Difference between expected and actual behavior

I expected to be able to move. I didn't. I blame coders.

#### Steps to reproduce

1. Play.
2. Something happens.
3. You can't move anymore.

#### Specific information for locating

No fucking idea what causes it.

#### Length of time in which bug has been known to occur

Since a week ago.

#### Client version, Server revision & Game ID

whatever the community server is running i can't be arsed

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
This could be your connection lagging out. Or the server being overloaded. Or a lot of other things. 
If you can't tie it to a change in the game code I don't think its really an issue we can do anything about.
