### ISSUE TITLE
'Join Game' button only works for 50% of players

### ISSUE THREAD

**Issue by genessee-forgot-his-password-again** [PersistentSS13/Nebula#258]
#### Description of issue

The join game button doesn't work.

#### Difference between expected and actual behavior

I expected to be able to play the codebase. I can't.

#### Steps to reproduce

1. Join game
2. Try to join game
3. Try to join game
4. Please
5. Join GAME
6. be unable to join ga,e

#### Specific information for locating

join game

#### Length of time in which bug has been known to occur

Since a 3 days ago.

#### Client version, Server revision & Game ID

whatever the test server is running

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Tetsukiba** [comment]
Are you getting the "aRe yoU sUre you want join?" prompt

**Comment by PsyCommando** [comment]
I'm pretty sure that bug was known at the time. And I don't think it happens anymore. But I'll need confirmation.
