### ISSUE TITLE
Plating eats all atmosphere

### ISSUE THREAD

**Issue by genessee-forgot-his-password-again** [PersistentSS13/Nebula#260]
#### Description of issue

Plating tiles eat all atmosphere no matter what as though they were space tiles. Does not seem to effect tiles with floor tiles.

#### Difference between expected and actual behavior

I expected the codebase to fucking work. It didn't.

#### Steps to reproduce

1. Spawn in
2. Go to solars room, which has plating
3. Observe the fact that you now have no air in your lungs

#### Length of time in which bug has been known to occur

11/24/2021

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 6a233e51aa58c78b8e5be154b5583f1d106b6dfd - dev - 2021-11-24
Game ID: cfa-bJVA
Current map: Kleibkhar Colony

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
That's a problem with that particular map most likely. Will fix.

**Comment by PsyCommando** [comment]
That was a kleibkhar base turf issue. And also due to how plating turfs are picked.
Should work now. But will need inverstigation.
