### ISSUE TITLE
Cables ignite flammables

### ISSUE THREAD

**Issue by PipeWizard** [PersistentSS13/Nebula#268]
#### Description of idea
Leaving flammable items on top of sources of heat (cabling) will ignite (similar to hitting a piece of paper with a lighter) and burn it. 
 An example of this is leaving clothing on top of exposed cabling which will eventually lead to it catching fire and burning to ash.  **NOTE** this would **not** cause an atmospheric fire resulting in potential widespread destruction.  It is simply the destruction of the flammable item.

#### How would this improve gameplay
This would help combat the issue of over a long period of time, items populate to such a degree you will never have to use any related fabricator again.  This idea also helps encourage players through a minor annoyance to tile rooms, generally clean a little bit, and to keep trash outside of maintenance.  As for OOC implications, any encouragement to recycle excess items helps save on saving time and keeps the server running smoothly.

**Comment by PsyCommando** [comment]
That would be very expensive to implement and kind of infuriating?
A better approach is to implement some sort of durability and decay systems.
