### ISSUE TITLE
IV Bags Unobtainable

### ISSUE THREAD

**Issue by PipeWizard** [PersistentSS13/Nebula#330]
#### Description of issue
IV bags cannot be obtained outside of spawning. (Searched on the git and didn't find anything as well.  If I'm blind, just close lol)

/obj/item/chems/ivbag
bloodpack.dm

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by AGasCanister** [comment]
![image](https://user-images.githubusercontent.com/55928412/178256124-a5860b7c-559b-4a57-bc53-dede8ac9d598.png)
![image](https://user-images.githubusercontent.com/55928412/178256192-c6c4fc2d-72e4-41ad-8712-74baf346fec9.png)
Cartridges can also be made with plastic
