### ISSUE TITLE
Unable to remove Areas

### ISSUE THREAD

**Issue by thedarkcrusader** [PersistentSS13/Nebula#347]
#### Description of issue
When trying to remove an already existing area from a location using blueprints an error message will pop up saying the area is not visible on the blueprints 

#### Difference between expected and actual behavior

Area would be removed if it works it is not removed and displays and error 

#### Steps to reproduce

Place Area
Attempt to remove area
Gives you An error 

#### Client version, Server revision & Game ID
5.4.1585 Stable branch test server

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
This probably was fixed upstream by now. Closing.
