### ISSUE TITLE
Top Hot not visible on  humans

### ISSUE THREAD

**Issue by thedarkcrusader** [PersistentSS13/Nebula#348]
#### Description of issue
Tophat is not visible on the sprite 

#### Difference between expected and actual behavior
When you wear something it should show on the sprite it does not

#### Steps to reproduce

find a top hat
Wear a tophat 
unable to wear tophat

#### Specific information for locating

<html>
<body>

/obj/item/clothing/head/that
31

<br class="Apple-interchange-newline">
</body>
</html>

#### Length of time in which bug has been known to occur
All the time

#### Client version, Server revision & Game ID

 Current stable version test server

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by PsyCommando** [comment]
Was fixed upstream.
