### ISSUE TITLE
Digital bulletin boards

### ISSUE THREAD

**Issue by Hashpiker** [PersistentSS13/Nebula#38]
Reason why:
A replacement for the old cork paper bulletin boards is needed. old cork boards required their sprites to be saved or they appeared empty on loading. Limited space on the boards meant only four pieces of paper could be attached at any one time.

Basic features needed:
An unnetworked(and/or networked?)bulletin board capable of displaying text in the form of a selectable entry.

Persistence features could include:
-being able to set an auto delete date to free up saving time or 
-digitally edit entry’s.

Uses for the digital bulletin board include: 
-a place to post public business announcements that will persist and inform people who may not have been around when an accouncement was publicly made on any kind of chat medium.
-price sheets for store inventory’s for employees or customers 
-menus or drink lists and/or pricing for employees or customers 
-recruitment postings.
-Purchasing lists for company’s that wish to buy materials or finished goods from other groups.
-advertising for small businesses that have no established location.

**Comment by PsyCommando** [comment]
Archiving this for now.
