### ISSUE TITLE
Fabricator material storage is not updated by design files

### ISSUE THREAD

**Issue by out-of-phaze** [PersistentSS13/Nebula#406]
#### Description of issue
Fabricator material storage automatically updates in `refresh_design_cache()` but this doesn't work for design files on a network mainframe.

#### Difference between expected and actual behavior
It should update to accept materials as soon as the design cache is updated.

#### Steps to reproduce
I'm only going off of secondhand info here, but this is my best attempt:
1. Create a design file for something that takes a material not in the default materials on a protolathe, like a subspace ansible that takes uranium.
2. Try to insert that material into the fabricator.
3. Rejected. Also, it doesn't show up in the list of materials.

#### Specific information for locating
Confirmed to happen for protolathes and uranium, and circuit imprinters and copper/plastic.

#### Length of time in which bug has been known to occur
Since the fabricator material storage change was made upstream.

#### Client version, Server revision & Game ID

![image](https://cdn.discordapp.com/attachments/678826323728400394/1077768556722262066/image.png)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by pitaden** [comment]
Several people ran into the same issue while shiptest was hosting outreach code
