### ISSUE TITLE
Megatest List

### ISSUE THREAD

**Issue by Andrew-Fall** [PersistentSS13/Nebula#43]
### General
- [ ] Fusion Engine Running
- [ ] Fusion Engine Network
- [ ] Labelled Fridge
- [ ] Clothing
- [ ] Storage
- [ ] Liquid Storage
- [ ] Welders
- [ ] Showers
- [ ] Doors
- [ ] Plants
- [ ] Personal Air Tanks
- [ ] Exosuits
- [ ] Exosuit Construction Phases
- [ ] Robots
- [ ] FBP Players
- [ ] Supermatter Reactor Energy States
- [ ] Prosthetics
### Atmospherics
- [ ] Zone air contents
- [ ] Pipeline air contents
- [ ] Trinary devices (mixers, filters)
- [ ] Binary devices (pumps, valves)
- [ ] Omni-devices
- [ ] Portables Connectors
- [ ] Portable Atmos. Devices
- [ ] Air Alarms settings
- [ ] Injector, Vent, Scrubber radio settings
- [ ] Air Control consoles
### Computers
- [ ] Crew Record Files
- [ ] Grant Files
- [ ] Text Files
- [ ] Programs Installed
- [ ] Access Control Lists

**Comment by PsyCommando** [comment]
Mega old.
