### ISSUE TITLE
Science Overhaul

### ISSUE THREAD

**Issue by biscuitWizard** [PersistentSS13/Nebula#46]
Machines:
* Destructive Analyzer: When provided an item, destroying an item will produce a blueprint. When provided an experiment, will check the experiment is complete and produce a result file.
* Research Computer: Used to load blueprints and produce experiments. As well as to read result files.
* Protolathe: Used to print experiment casings.

Files:
* Blueprint: Has instability, compression, power efficiency, material efficiency, time efficiency variables. Instructions to build an item. Can be iterated on and improved.
* Experiment: an in-progress experiment. Can be turned into a result by DA-ing the experiment.
* Code fragment: Used for experiments. Generated by computer developers on modular computers.

Process:
1. An item is put into a destructive analyzer and scanner. If the resulting item has a fabricator recipe, a blueprint file is created at worst possible spec.
2. The blueprint is loaded into a research computer. Three experiments are presented to a user. Each experiment offers to improve one variable of the blueprint. They give a recipe list for the experiment. New recipes can be generated the next time the server reboots.
3. an experiment is chosen. The experiment file is created. The recipe list will list N number of ingredients, and the ingredients listed in a format that shows a required tech-origin-level.
4. The protolathe is loaded with steel and the experiment casing is printed with the ID code of the experiment as the name of the object. It is a /datum/extension/assembly with required parts equal to the experiment's output.
5. /obj/items with a tech origin level meeting one of the recipe's prerequisites are kitbashed into the casing.
6. At the same time, a developer using a sufficiently powerful modular_computer and skill creates code fragment files. These files are uploaded to a portable disk and kitbashed into the casing.
7. The completed casing it put into the destructive analyzer.
8. The item is destroyed from the experiment view window, and the blueprint file is upgraded.

Repeat.

**Invention Mode**
Invention Mode is you are given a casing and can throw in up to three items. The highest of each tech_origin is used from each item. Then you wire it and weld it together. The code fragment you throw in it will give it a +1 to a tech_origin corresponding to the type of code fragment put in. Then you DA it. and a random item that is equal to or less than the tech_origins you provided will generate a blueprint

**Comment by biscuitWizard** [comment]
Link issue #46

**Comment by Andrew-Fall** [comment]
Resolved with #48
