### ISSUE TITLE
Stray Pixel on Armor Vest Sprite

### ISSUE THREAD

**Issue by genessee-forgot-his-password-again** [PersistentSS13/Nebula#462]
#### Description of issue

stray pixel on obj/item/clothing/suit/armor/vest

![image](https://github.com/PersistentSS13/Nebula/assets/80235421/13292a83-8a10-43e8-b51f-4ca4a32909f6)

#### Difference between expected and actual behavior

THE PIXELS! WHAT DO THEY MEAN?

#### Steps to reproduce

put on the vest
face forward

#### Specific information for locating

obj/item/clothing/suit/armor/vest

#### Length of time in which bug has been known to occur

probably as long as the vest has been resprited

#### Client version, Server revision & Game ID

most recent stable

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by questionable-masquarade** [comment]
@genessee-forgot-his-password-again PR is merged feel free to check if issue is fixed and then close :)
