### ISSUE TITLE
Potential Sleeper duplication bug

### ISSUE THREAD

**Issue by NataKilar** [PersistentSS13/Nebula#495]
#### Description of issue
Sleepers may be capable of duplicating chemicals. Reported by N8-Toe

#### Steps to reproduce
Possibly occurs with patient in sleeper.

**Comment by genessee-forgot-his-password-again** [comment]
I suspect this is due to the sleeper in question spawning with chemicals rather than being built; maybe it's spawning a new set of chemicals every time its' loaded?
