### ISSUE TITLE
Implement Starting Vending Machines

### ISSUE THREAD

**Issue by biscuitWizard** [PersistentSS13/Nebula#57]
Implement vending machines /w infinite stock. These should be time-locked per user so only one kit can be bought a day. This time should immediately refresh if the user dies.

These kits cost money. They are explicitly for "starting" kits.

Require following variants of vending machine:

- Botany: Seeds & machines?
- Mining: Equipment? Satchels?
- Ship (Ship core circuitboard, gas thruster circuitboard)
- Medical: Injectables? Scalpels?
- Industrial: Some blueprints for machines, maybe some stacks of metals?

**Comment by N8-Toe** [comment]
https://gist.github.com/N8-Toe/e215a94296b72287a506d3f1ad1c0c49
supply kits
