### ISSUE TITLE
add asteroid fields

### ISSUE THREAD

**Issue by biscuitWizard** [PersistentSS13/Nebula#71]
when near a sector with asteroids, allow 'docking' to generate a mineable z-layer.

**Comment by biscuitWizard** [comment]
concerns: too many z levels.
too long to generate z-layer (20-40s on my dev machine)

fixes:
recycle z levels
pregenerate a few mining levels.

**Comment by HighTyrol** [comment]
What about a timer to access the z-level? unless they use an item to make access to it permentant you coul have the level degrade as you salvage. And then generate the next one before the current one is gone unless they are going for a perment. Give 10-30 minutes to mine on each level before it "collapses" or something. And then about 1-2 minutes before the current map ends starts generating a new one.

**Comment by PsyCommando** [comment]
Been handled a bit differently.
