### ISSUE TITLE
Add Bluespace Phase Drive

### ISSUE THREAD

**Issue by biscuitWizard** [PersistentSS13/Nebula#77]
Bluespace phase drive is an expensive, power hungry device that can be put on shuttles.

Things to Add:

- Drive Core (/obj/item)
- Phase Drive Circuit Board (/obj/item)
- Phase Drive Machine (/obj/machine)
- Phase Drive Console (/obj/machine/computer)
- Phase Drive Console Circuit (/obj/item)
- Exotic Matter Fuel Assembly (/obj/item)

When activated the drive will require an instant power usage of 2 megawatts - (250kw per drive core not counting the first. Max 5.) It will then have a spin up period of 5 minutes. Active power usage will become 1 megawatt. After which the drive activates and consumes another 2 megawatts - (250kw per drive core not counting the first. Max 5.) and an inserted exotic matter fuel assembly.

The ship is moved to a new transit level and cannot be visited. It is out of reality. Anything docked with the ship will not come with it. This cannot be used at all on a station z_level or exoplanet.

While the drive is active, it will consume 750kw (-25kw per drive core) actively.

If the drive loses power while activated, an EMP effect should hit the whole ship, and possibly some random (very small) explosions. All components in the drive core should be damaged. Emergency shutoff in the console should produce the same effect.

The drive can be operated indefinitely as long as it has power.

**Comment by PsyCommando** [comment]
shunt drive?
