### ISSUE TITLE
Labels are not properly removed.

### ISSUE THREAD

**Issue by Viole7** [PersistentSS13/Nebula#99]
#### Description of issue
Labels added to items using the hand labeler are not correctly removed when attempting to do so. The message to the player fires but the label remains on the object, afterwards there is no further option to attempt removal.

#### Difference between expected and actual behavior
When clicking remove label, the label ought to be removed.

#### Steps to reproduce
Use a hand labeler to label any object. Right click the object and select remove label. The message will fire but the label that was added to the items name will remain.

#### Specific information for locating
Nebula/code/modules/paperwork/handlabeler.dm
Nebula/code/datums/extensions/label.dm

#### Length of time in which bug has been known to occur
No clue.

#### Client version, Server revision & Game ID
Latest as of 09/26/2020

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

**Comment by Viole7** [comment]
I've done some debugging and I think the problem stems from line 48 of label.dm. For some reason the text isn't being replaced properly and I don't know why.

**Comment by Viole7** [comment]
Issue is still present as of 1/1/2021 on the latest build.

**Comment by Tomsynth1** [comment]
Tried to replicate this, it seems to work fine on both base Neb and Persistence. I'm guessing it was quietly fixed upstream.

**Comment by PsyCommando** [comment]
Should definitely have been fixed after paperwork rework upstream.
